---
apiVersion: v1
kind: Service
metadata:
  name: ssh
spec:
  ports:
  - name: ssh
    port: 22
  selector:
    app: ssh
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssh
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ssh
  template:
    metadata:
      labels:
        app: ssh
    spec:
      containers:
      - image: testcontainers/sshd:1.2.0
        name: ssh
